[workspace]
resolver = "2"
members = ["cli", "common", "ic-canister"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
ahash = { version = "0.8", default-features = false }
anyhow = "1.0"
base32 = "0.5"
base64 = "0.22"
borsh = { version = "1.5", features = ["derive"] }
ciborium = "0.2"
candid = "0.10"
chrono = "0.4"
clap = "4.5"
crc32fast = "1.4"
data-encoding = "2.6"
derp = "0.0.14"
dcc-common = { path = "common" }
dirs = "5.0"
ed25519-dalek = { version = "2", default-features = false, features = [
    "alloc",
    "digest",
    "pkcs8",
    "pem",
] }
env_logger = "0.11"
fs-err = "2.11"
hex = "0.4"
hmac = "0.12"
ic-agent = "0.37"
ic-canister-log = "0.2"
ic-cdk = "0.16"
ic-certification = "2.6"
ic-metrics-encoder = "1.1"
ic-cdk-timers = "0.10"
icrc-ledger-types = "0.1"
indexmap = "2.5"
ledger-map = { path = "../ledger-map" }
# ledger-map = { git = "https://github.com/decent-cloud/ledger-map.git", branch = "main" }
log = "0.4"
memmap2 = "0.9"
num-bigint = { version = "0.4", default-features = false, features = ["serde"] }
pem = "3.0"
pkcs8 = "0.10"
pocket-ic = "4"
serde = "1.0"
serde_bytes = "0.11"
serde_json = { version = "1.0", features = ["preserve_order"] }
serde_yaml_ng = "0.10"
sha2 = "0.10"
strum = { version = "0.26", features = ["derive"] }
strum_macros = "0.26"
strsim = "0.11"
tabular = "0.2"
tempfile = "3"
tiny-bip39 = "1.0"
tokio = { version = "1", features = ["full"] }
which = "6.0"
