[workspace]
resolver = "2"
members = ["cli", "common", "ic-canister"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
ahash = { version = "0.8.11", default-features = false }
anyhow = "1.0.81"
base32 = "0.5.0"
base64 = "0.22.0"
borsh = { version = "1.3.1", features = ["derive"] }
ciborium = "0.2.2"
candid = "0.10.5"
chrono = "0.4.35"
clap = "4.5.3"
crc32fast = "1.4.0"
data-encoding = "2.5.0"
derp = "0.0.14"
dcc-common = { path = "common" }
dirs = "5.0.1"
ed25519-dalek = { version = "2", default-features = false, features = [
    "alloc",
    "digest",
    "pkcs8",
    "pem",
] }
env_logger = "0.11.3"
flate2 = { version = "1.0", features = [
    "rust_backend",
], default-features = false }
fs-err = "2.11.0"
hex = "0.4.3"
hmac = "0.12.1"
ic-agent = "0.36.0"
ic-canister-log = "0.2.0"
ic-cdk = "0.15.0"
ic-certification = "2.5.0"
ic-metrics-encoder = "1.1.1"
ic-cdk-timers = "0.9.0"
icrc-ledger-types = "0.1.5"
indexmap = "2.2.5"
ledger-map = { path = "../ledger-map" }
# ledger-map = { git = "https://github.com/decent-cloud/ledger-map.git", branch = "main" }
log = "0.4.21"
memmap2 = "0.9.4"
num-bigint = { version = "0.4.4", default-features = false, features = [
    "serde",
] }
pem = "3.0.4"
pkcs8 = "0.10.2"
pocket-ic = "3.1.0"
serde = "1.0.197"
serde_bytes = "0.11.14"
serde_json = { version = "1.0.114", features = ["preserve_order"] }
serde_yaml_ng = "0.10.0"
sha2 = "0.10.8"
strum = { version = "0.26.2", features = ["derive"] }
strum_macros = "0.26.2"
tabular = "0.2.0"
tempfile = "3.10.1"
tiny-bip39 = "1.0.0"
tokio = { version = "1.36.0", features = ["full"] }
which = "6.0.1"
