[env]
RUST_BACKTRACE = "1"

[config]
default_to_workspace = false
on_error_task = "post-test"
unstable_features = ["CTRL_C_HANDLING"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.canister]
command = "dfx"
args = ["build", "--all"]
cwd = "./ic-canister/"

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.clippy-canister]
command = "cargo"
args = ["clippy", "--target=wasm32-unknown-unknown"]
cwd = "./ic-canister/"

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.pre-test]
script = '''
#!/usr/bin/env bash
set -eEuo pipefail

cd ic-canister
dfx stop || true
dfx start --background
while true; do
    dfx ping local && break;
    sleep 1;
done;
'''

[tasks.test]
dependencies = ["pre-test", "build", "canister"]

[tasks.post-test]
script = '''
#!/usr/bin/env bash
set -eEuo pipefail

(cd ic-canister && dfx stop)
'''

[tasks.pytest]
script = '''
#!/usr/bin/env bash
set -eEuo pipefail

pixi install
pixi run pytest
'''

[tasks.all]
dependencies = [
    "format",
    "canister",
    "clippy",
    "clippy-canister",
    "build",
    "pre-test",
    "test",
    "pytest",
    "post-test",
]
