[package]
name = "np-profile"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_yaml_ng = { workspace = true }
np-yaml-search = { path = "../np-yaml-search" }
