[package]
name = "np-profile"
version.workspace = true
edition.workspace = true

[dependencies]
borsh.workspace = true
fs-err = { workspace = true }
np-json-search = { path = "../np-json-search" }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml_ng = { workspace = true }
