[package]
name = "np-yaml-search"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
parse-size.workspace = true
regex.workspace = true
serde_yaml_ng.workspace = true
