name: Build and Push Docker Image

on:
  push:
    branches:
      - main # or specify any other branch you want to trigger the build
  workflow_dispatch: # allows for manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/ci-image:latest

      - name: Verify Docker image
        shell: bash
        run: |
          set -eExuo pipefail
          IMAGE=ghcr.io/${{ github.repository }}/ci-image:latest
          docker pull $IMAGE
          docker run --rm $IMAGE cargo --version
          docker run --rm $IMAGE cargo-make --version
