name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # allows for manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .github/container
          push: true
          tags: ci-cargo:latest

      - name: Verify Docker image
        shell: bash
        run: |
          set -eExuo pipefail
          IMAGE=ghcr.io/${{ github.repository }}/ci-cargo:latest
          docker pull $IMAGE
          docker run --rm $IMAGE --version
          docker run --rm $IMAGE make --version
