name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/ci-image:latest

    steps:
      - uses: actions/checkout@v4
      - name: Check dfx
        run: |
          set -eExuo pipefail
          # source "$HOME/.local/share/dfx/env"
          dfx --version
      - name: Clone Ledger Map
        shell: bash
        run: |
          set -eExuo pipefail
          (
            cd ..
            git clone --depth 1 https://github.com/decent-cloud/ledger-map.git
            cd -
          )
      - name: Build and test
        shell: bash
        run: |
          set -eExuo pipefail
          source "$HOME/.local/share/dfx/env"
          cargo make
