name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/ci-image@sha256:afc4437e594a9c314e834d1037640ff9e41ad69b233f87f69dd2e695ce666a1e

    steps:
      - uses: actions/checkout@v4
      - name: Check dfx
        shell: bash
        run: dfx --version
      - name: Clone Ledger Map
        shell: bash
        run: |
          set -eExuo pipefail
          (
            cd ..
            git clone --depth 1 https://github.com/decent-cloud/ledger-map.git
            cd -
          )
      - name: Build and test
        shell: bash
        run: cargo make
