name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/ci-image@sha256:c2b3d3b233ce5093460ca744370074d51eba26e91c3f41ab4785bf1a123f2b2a

    steps:
      - uses: actions/checkout@v4
      - name: dfxvm init
        run: |
          echo "dfxvm requires the default version to be set once after starting the container (bug!)"
          dfxvm default 0.22.0
          dfx --version
      - name: Clone Ledger Map
        shell: bash
        run: |
          set -eExuo pipefail
          (
            cd ..
            git clone --depth 1 https://github.com/decent-cloud/ledger-map.git
            cd -
          )
      - name: Build and test
        env:
          # dfx requires XDG_DATA_HOME to be set
          XDG_DATA_HOME: /usr/local
        run: /tini -s -- cargo make
