name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  XDG_DATA_HOME: /usr/local

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/ci-image@sha256:6b789968bd7db8591b8f2847f81bc89c4a8a68b3772569e16eb7ba253f8b8a9d

    steps:
      - uses: actions/checkout@v4
      - name: Check dfx
        shell: bash
        run: dfx --version
      - name: Clone Ledger Map
        shell: bash
        run: |
          set -eExuo pipefail
          (
            cd ..
            git clone --depth 1 https://github.com/decent-cloud/ledger-map.git
            cd -
          )
      - name: Build and test
        shell: bash
        run: cargo make
