name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dfx
      run: sh -m -c "$(curl -fsSL https://internetcomputer.org/install.sh)"
      shell: bash
    - name: Install cargo-make
      run: cargo install --force cargo-make
    - name: Build and test
      run: cargo make
